/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreinosRouteImport } from './routes/treinos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HabitosRouteImport } from './routes/habitos'
import { Route as EvolucaoRouteImport } from './routes/evolucao'
import { Route as DietaRouteImport } from './routes/dieta'
import { Route as IndexRouteImport } from './routes/index'

const TreinosRoute = TreinosRouteImport.update({
  id: '/treinos',
  path: '/treinos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitosRoute = HabitosRouteImport.update({
  id: '/habitos',
  path: '/habitos',
  getParentRoute: () => rootRouteImport,
} as any)
const EvolucaoRoute = EvolucaoRouteImport.update({
  id: '/evolucao',
  path: '/evolucao',
  getParentRoute: () => rootRouteImport,
} as any)
const DietaRoute = DietaRouteImport.update({
  id: '/dieta',
  path: '/dieta',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dieta': typeof DietaRoute
  '/evolucao': typeof EvolucaoRoute
  '/habitos': typeof HabitosRoute
  '/login': typeof LoginRoute
  '/treinos': typeof TreinosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dieta': typeof DietaRoute
  '/evolucao': typeof EvolucaoRoute
  '/habitos': typeof HabitosRoute
  '/login': typeof LoginRoute
  '/treinos': typeof TreinosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dieta': typeof DietaRoute
  '/evolucao': typeof EvolucaoRoute
  '/habitos': typeof HabitosRoute
  '/login': typeof LoginRoute
  '/treinos': typeof TreinosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dieta' | '/evolucao' | '/habitos' | '/login' | '/treinos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dieta' | '/evolucao' | '/habitos' | '/login' | '/treinos'
  id:
    | '__root__'
    | '/'
    | '/dieta'
    | '/evolucao'
    | '/habitos'
    | '/login'
    | '/treinos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DietaRoute: typeof DietaRoute
  EvolucaoRoute: typeof EvolucaoRoute
  HabitosRoute: typeof HabitosRoute
  LoginRoute: typeof LoginRoute
  TreinosRoute: typeof TreinosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treinos': {
      id: '/treinos'
      path: '/treinos'
      fullPath: '/treinos'
      preLoaderRoute: typeof TreinosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habitos': {
      id: '/habitos'
      path: '/habitos'
      fullPath: '/habitos'
      preLoaderRoute: typeof HabitosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evolucao': {
      id: '/evolucao'
      path: '/evolucao'
      fullPath: '/evolucao'
      preLoaderRoute: typeof EvolucaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dieta': {
      id: '/dieta'
      path: '/dieta'
      fullPath: '/dieta'
      preLoaderRoute: typeof DietaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DietaRoute: DietaRoute,
  EvolucaoRoute: EvolucaoRoute,
  HabitosRoute: HabitosRoute,
  LoginRoute: LoginRoute,
  TreinosRoute: TreinosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
